# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamma_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import kappa.gamma.proto.status_pb2 as status__pb2
import kappa.gamma.proto.deployment_pb2 as deployment__pb2
import kappa.gamma.proto.repository_pb2 as repository__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamma_service.proto',
  package='kappa',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13gamma_service.proto\x12\x05kappa\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0cstatus.proto\x1a\x10\x64\x65ployment.proto\x1a\x10repository.proto\"4\n\x13HealthCheckResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.kappa.Status\"P\n\x1eGetGammaServiceVersionResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.kappa.Status\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xc5\x08\n\x05Gamma\x12\x41\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1a.kappa.HealthCheckResponse\x12W\n\x16GetGammaServiceVersion\x12\x16.google.protobuf.Empty\x1a%.kappa.GetGammaServiceVersionResponse\x12P\n\x0f\x41pplyDeployment\x12\x1d.kappa.ApplyDeploymentRequest\x1a\x1e.kappa.ApplyDeploymentResponse\x12S\n\x10\x44\x65leteDeployment\x12\x1e.kappa.DeleteDeploymentRequest\x1a\x1f.kappa.DeleteDeploymentResponse\x12J\n\rGetDeployment\x12\x1b.kappa.GetDeploymentRequest\x1a\x1c.kappa.GetDeploymentResponse\x12Y\n\x12\x44\x65scribeDeployment\x12 .kappa.DescribeDeploymentRequest\x1a!.kappa.DescribeDeploymentResponse\x12P\n\x0fListDeployments\x12\x1d.kappa.ListDeploymentsRequest\x1a\x1e.kappa.ListDeploymentsResponse\x12;\n\x08\x41\x64\x64\x42\x65nto\x12\x16.kappa.AddBentoRequest\x1a\x17.kappa.AddBentoResponse\x12\x44\n\x0bUpdateBento\x12\x19.kappa.UpdateBentoRequest\x1a\x1a.kappa.UpdateBentoResponse\x12;\n\x08GetBento\x12\x16.kappa.GetBentoRequest\x1a\x17.kappa.GetBentoResponse\x12\x65\n\x16\x44\x61ngerouslyDeleteBento\x12$.kappa.DangerouslyDeleteBentoRequest\x1a%.kappa.DangerouslyDeleteBentoResponse\x12>\n\tListBento\x12\x17.kappa.ListBentoRequest\x1a\x18.kappa.ListBentoResponse\x12\x41\n\x0bListProject\x12\x16.google.protobuf.Empty\x1a\x1a.kappa.ListProjectResponse\x12V\n\x11\x43ontainerizeBento\x12\x1f.kappa.ContainerizeBentoRequest\x1a .kappa.ContainerizeBentoResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,status__pb2.DESCRIPTOR,deployment__pb2.DESCRIPTOR,repository__pb2.DESCRIPTOR,])




_HEALTHCHECKRESPONSE = _descriptor.Descriptor(
  name='HealthCheckResponse',
  full_name='kappa.HealthCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='kappa.HealthCheckResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=161,
)


_GETGAMMASERVICEVERSIONRESPONSE = _descriptor.Descriptor(
  name='GetGammaServiceVersionResponse',
  full_name='kappa.GetGammaServiceVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='kappa.GetGammaServiceVersionResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='kappa.GetGammaServiceVersionResponse.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=243,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='kappa.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='kappa.Chunk.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=269,
)

_HEALTHCHECKRESPONSE.fields_by_name['status'].message_type = status__pb2._STATUS
_GETGAMMASERVICEVERSIONRESPONSE.fields_by_name['status'].message_type = status__pb2._STATUS
DESCRIPTOR.message_types_by_name['HealthCheckResponse'] = _HEALTHCHECKRESPONSE
DESCRIPTOR.message_types_by_name['GetGammaServiceVersionResponse'] = _GETGAMMASERVICEVERSIONRESPONSE
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'gamma_service_pb2'
  # @@protoc_insertion_point(class_scope:kappa.HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)

GetGammaServiceVersionResponse = _reflection.GeneratedProtocolMessageType('GetGammaServiceVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETGAMMASERVICEVERSIONRESPONSE,
  '__module__' : 'gamma_service_pb2'
  # @@protoc_insertion_point(class_scope:kappa.GetGammaServiceVersionResponse)
  })
_sym_db.RegisterMessage(GetGammaServiceVersionResponse)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'gamma_service_pb2'
  # @@protoc_insertion_point(class_scope:kappa.Chunk)
  })
_sym_db.RegisterMessage(Chunk)



_GAMMA = _descriptor.ServiceDescriptor(
  name='Gamma',
  full_name='kappa.Gamma',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=1365,
  methods=[
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='kappa.Gamma.HealthCheck',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_HEALTHCHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGammaServiceVersion',
    full_name='kappa.Gamma.GetGammaServiceVersion',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETGAMMASERVICEVERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ApplyDeployment',
    full_name='kappa.Gamma.ApplyDeployment',
    index=2,
    containing_service=None,
    input_type=deployment__pb2._APPLYDEPLOYMENTREQUEST,
    output_type=deployment__pb2._APPLYDEPLOYMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteDeployment',
    full_name='kappa.Gamma.DeleteDeployment',
    index=3,
    containing_service=None,
    input_type=deployment__pb2._DELETEDEPLOYMENTREQUEST,
    output_type=deployment__pb2._DELETEDEPLOYMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeployment',
    full_name='kappa.Gamma.GetDeployment',
    index=4,
    containing_service=None,
    input_type=deployment__pb2._GETDEPLOYMENTREQUEST,
    output_type=deployment__pb2._GETDEPLOYMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DescribeDeployment',
    full_name='kappa.Gamma.DescribeDeployment',
    index=5,
    containing_service=None,
    input_type=deployment__pb2._DESCRIBEDEPLOYMENTREQUEST,
    output_type=deployment__pb2._DESCRIBEDEPLOYMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListDeployments',
    full_name='kappa.Gamma.ListDeployments',
    index=6,
    containing_service=None,
    input_type=deployment__pb2._LISTDEPLOYMENTSREQUEST,
    output_type=deployment__pb2._LISTDEPLOYMENTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddBento',
    full_name='kappa.Gamma.AddBento',
    index=7,
    containing_service=None,
    input_type=repository__pb2._ADDBENTOREQUEST,
    output_type=repository__pb2._ADDBENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBento',
    full_name='kappa.Gamma.UpdateBento',
    index=8,
    containing_service=None,
    input_type=repository__pb2._UPDATEBENTOREQUEST,
    output_type=repository__pb2._UPDATEBENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBento',
    full_name='kappa.Gamma.GetBento',
    index=9,
    containing_service=None,
    input_type=repository__pb2._GETBENTOREQUEST,
    output_type=repository__pb2._GETBENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DangerouslyDeleteBento',
    full_name='kappa.Gamma.DangerouslyDeleteBento',
    index=10,
    containing_service=None,
    input_type=repository__pb2._DANGEROUSLYDELETEBENTOREQUEST,
    output_type=repository__pb2._DANGEROUSLYDELETEBENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListBento',
    full_name='kappa.Gamma.ListBento',
    index=11,
    containing_service=None,
    input_type=repository__pb2._LISTBENTOREQUEST,
    output_type=repository__pb2._LISTBENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListProject',
    full_name='kappa.Gamma.ListProject',
    index=12,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=repository__pb2._LISTPROJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ContainerizeBento',
    full_name='kappa.Gamma.ContainerizeBento',
    index=13,
    containing_service=None,
    input_type=repository__pb2._CONTAINERIZEBENTOREQUEST,
    output_type=repository__pb2._CONTAINERIZEBENTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMMA)

DESCRIPTOR.services_by_name['Gamma'] = _GAMMA

# @@protoc_insertion_point(module_scope)
