ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim AS compile-image
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc

ARG KAPPA_VERSION
ENV KAPPA_VERSION=$KAPPA_VERSION

RUN python -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

# pre-install Kappa requirements
#RUN pip install kappa[model_server]==$KAPPA_VERSION --no-cache-dir
RUN pip install http://129.159.115.226:9999/Kappa-0.0.1-py3-none-any.whl --no-cache-dir
COPY entrypoint.sh .

# multi-stage build to shave dependency cost
FROM python:${PYTHON_VERSION}-slim AS build-image
COPY --from=compile-image /opt/venv /opt/venv
COPY --from=compile-image entrypoint.sh /usr/local/bin

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

ENTRYPOINT [ "entrypoint.sh" ]
CMD ["kappa", "serve-gunicorn", "/bento"]
