contact_links:
  - name: Kappa Discussions
    url: https://github.com/bentoml/Kappa/discussions
    about: Please ask general questions here.
  - name: Kappa Slack Community
    url: https://join.slack.com/t/bentoml/shared_invite/enQtNjcyMTY3MjE4NTgzLTU3ZDc1MWM5MzQxMWQxMzJiNTc1MTJmMzYzMTYwMjQ0OGEwNDFmZDkzYWQxNzgxYWNhNjAxZjk4MzI4OGY1Yjg
    about: For connecting with others in the community
  - name: Kappa Enterprise Support
    url: contact@bentoml.ai
    about: Contact the Kappa team and learn more
