{{- if .Values.postgres.enabled -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamma-postgres-pv-volume
  labels:
    type: local
    app: gamma-postgres
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storageCapacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: {{ .Values.postgres.pvReclaimPolicy }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gamma-postgres-pv-claim
  labels:
    app: gamma-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgres.storageCapacity }}
{{- end -}}